package model;

import java.time.LocalDate;

/**
 * Model class for a BloodUnit.
 * This class corresponds to the 'BloodUnits' table in the database.
 * Its only job is to hold data for a single blood unit.
 */
public class BloodUnit {

    // --- Fields ---
    // These are private to protect the data (Encapsulation).
    private int bloodId;
    private String bloodType;
    private int quantity;
    private LocalDate donationDate;
    private LocalDate expiryDate;
    private int donorId; // Foreign Key

    // --- Constructors ---

    /**
     * Default constructor.
     */
    public BloodUnit() {
    }

    /**
     * Full constructor for retrieving a BloodUnit from the database
     * (e.g., in our DAO).
     */
    public BloodUnit(int bloodId, String bloodType, int quantity, LocalDate donationDate, LocalDate expiryDate, int donorId) {
        this.bloodId = bloodId;
        this.bloodType = bloodType;
        this.quantity = quantity;
        this.donationDate = donationDate;
        this.expiryDate = expiryDate;
        this.donorId = donorId;
    }

    /**
     * Constructor for creating a new BloodUnit in the application
     * (ID will be auto-generated by the database).
     */
    public BloodUnit(String bloodType, int quantity, LocalDate donationDate, LocalDate expiryDate, int donorId) {
        this.bloodType = bloodType;
        this.quantity = quantity;
        this.donationDate = donationDate;
        this.expiryDate = expiryDate;
        this.donorId = donorId;
    }

    // --- Getters and Setters ---
    // These are the public "gatekeepers" to access the private fields.

    public int getBloodId() {
        return bloodId;
    }

    public void setBloodId(int bloodId) {
        this.bloodId = bloodId;
    }

    public String getBloodType() {
        return bloodType;
    }

    public void setBloodType(String bloodType) {
        this.bloodType = bloodType;
    }

    public int getQuantity() {
        return quantity;
    }

    /**
     * Encapsulation in action:
     * We can add a rule to the setter to ensure the quantity
     * can never be set to a negative number, protecting our object's state.
     */
    public void setQuantity(int quantity) {
        if (quantity < 0) {
            this.quantity = 0; // Or throw an error, but never go negative
        } else {
            this.quantity = quantity;
        }
    }

    public LocalDate getDonationDate() {
        return donationDate;
    }

    public void setDonationDate(LocalDate donationDate) {
        this.donationDate = donationDate;
    }

    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    public int getDonorId() {
        return donorId;
    }

    public void setDonorId(int donorId) {
        this.donorId = donorId;
    }

    // --- toString() Method ---
    @Override
    public String toString() {
        return "BloodUnit{" +
                "bloodId=" + bloodId +
                ", bloodType='" + bloodType + '\'' +
                ", quantity=" + quantity +
                ", donationDate=" + donationDate +
                ", expiryDate=" + expiryDate +
                ", donorId=" + donorId +
                '}';
    }
}