-- 1. Create the database
-- This command creates your database if it doesn't already exist.
CREATE DATABASE IF NOT EXISTS blood_bank_db;

-- 2. Use the database
-- This command selects your database so all aql subsequent commands run against it.
USE blood_bank_db;

-- 3. Create the Donors table
-- This table stores all donor information, as you designed.
-- 'donor_id' is the Primary Key (PK) that auto-increments.
-- Added 'NOT NULL' to 'name' as per your validation rules.
CREATE TABLE IF NOT EXISTS Donors (
    donor_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(50),
    blood_type VARCHAR(10) NOT NULL,
    date_registered DATE NOT NULL
);

-- 4. Create the BloodUnits table
-- This table tracks the blood inventory.
-- 'blood_id' is the PK.
-- 'donor_id' is a Foreign Key (FK) that links to the 'Donors' table.
-- We add 'ON DELETE SET NULL' so that if a donor is deleted, the blood unit record remains,
-- but the link to the donor is removed (set to NULL). This prevents data loss.
CREATE TABLE IF NOT EXISTS BloodUnits (
    blood_id INT AUTO_INCREMENT PRIMARY KEY,
    blood_type VARCHAR(10) NOT NULL,
    quantity INT NOT NULL,
    donation_date DATE NOT NULL,
    expiry_date DATE NOT NULL,
    donor_id INT,
    FOREIGN KEY (donor_id) REFERENCES Donors(donor_id) ON DELETE SET NULL
);

-- 5. Create the BloodRequests table
-- This table tracks all incoming requests for blood.
-- 'fulfilled' is a BOOLEAN (which MySQL often treats as TINYINT(1))
-- We set a DEFAULT of 0 (false) for the 'fulfilled' status.
CREATE TABLE IF NOT EXISTS BloodRequests (
    request_id INT AUTO_INCREMENT PRIMARY KEY,
    blood_type VARCHAR(10) NOT NULL,
    quantity INT NOT NULL,
    request_date DATE NOT NULL,
    fulfilled BOOLEAN DEFAULT 0
);

-- 6. Create the Alerts table
-- This table will store the alerts generated by your system.
-- 'blood_id' is an FK that links to the 'BloodUnits' table.
-- 'ON DELETE CASCADE' means if a blood unit is deleted, its related alerts are also deleted.
-- We also set a DEFAULT 'Pending' for the status.
CREATE TABLE IF NOT EXISTS Alerts (
    alert_id INT AUTO_INCREMENT PRIMARY KEY,
    blood_id INT,
    alert_type VARCHAR(20) NOT NULL, -- "Near Expiry" or "Expired"
    date_generated DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'Pending', -- "Pending" or "Handled"
    FOREIGN KEY (blood_id) REFERENCES BloodUnits(blood_id) ON DELETE CASCADE
);